name: Tic Tac Toe
description: Let's play some Tic Tac Toe :D
inputs:
  token:
    description: Token
    required: true
runs:
  using: 'docker'
  image: 'docker://node:lts-alpine'
  entrypoint: 'node dist/index.js'

